sudo: required
services:
  -  docker

before_install: 
  - docker build -t ujjaldutta10/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ujjaldutta10/react-test npm test -- --coverage

after_success:
  - docker build -t ujjaldutta10/multi-client ./client
  - docker build -t ujjaldutta10/multi-nginx ./nginx
  - docker build -t ujjaldutta10/multi-server ./server
  - docker build -t ujjaldutta10/multi-worker ./worker 

#Login into Docker cli to push prod images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#Push prod images to docker hub
  - docker push ujjaldutta10/multi-client
  - docker push ujjaldutta10/multi-nginx
  - docker push ujjaldutta10/multi-server
  - docker push ujjaldutta10/multi-worker
